[package]
name = "blockchain_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
failure = "0.1.8"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.8"
